version: '3.8'

services:
  db:
    ports:
      - '5432:5432'
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_rental
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: book_rental
    depends_on:
      - db

volumes:
  db_data:
